### PR TITLE
Hide datepicker when user clicks outside it

### PR DESCRIPTION
**Pull request by FauzanKhan**
Added code to hide the datepicker whenever user clicks outside it i.e on body.

### CODE REVIEW

**Comment by fulup-bzh** [comment]
Thank you

**Comment by FauzanKhan** [comment]
Hey, I've developed easy to customize, material design version of your datepicker. you can check it out here - http://fauzankhan.github.io/angular-datepicker/ 
Would you like me to merge this one with your datepicker as well?

**Comment by fulup-bzh** [comment]
Look really nice, would you like to become a maintainer of DatePicker ?
Like that you could update DatePicker by yourself, which would even be simpler, no ?

By the way I also published on https://github.com/iotbzh/healthy-gulp-angular-foundation6 a much better framework to maintain HTML5/Angular/Foundation and on other work for me would be to port DatePicker on this template that is much better that the one I used for DatePicker/RangeSlider.

**Comment by FauzanKhan** [comment]
Sure. That'll be great! By the way I just made a bower package for the datepicker I mentioned, it goes by the name `fzn-angular-datepicker`. You can use it as a bower component now. 
Would look into your framework and see if I can contribute in any way :)

**Comment by fulup-bzh** [comment]
```
On 03/12/15 21:39, Fauzan Khan wrote:


  Sure. That'll be great! By the way I just made a bower package
    for the datepicker I mentioned, it goes by the name fzn-angular-datepicker.
    You can use it as a bower component now. 
    Would look into your framework and see if I can contribute in
    any way :)
  —
    Reply to this email directly or view
      it on GitHub.








You're in. Have fun.

Fulup

-- 

      Fulup Ar Foll, CEO
      Tel: +33.257.620.241 Mobile: +33.619.921.323
       www.iot.bzh
```

**Pull request merged**
